package com.yst.mall.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yst.mall.model.SysOperLog;

public interface SysOperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    int insert(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    int insertSelective(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    SysOperLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    int updateByPrimaryKeySelective(SysOperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_TEST
     *
     * @mbggenerated Tue Dec 05 14:05:16 CST 2017
     */
    int updateByPrimaryKey(SysOperLog record);

    /**
     * 获取所有日志
     * @param start 开始序号
     * @param end 结束序号
     * @param loginName 登录名
     * @param operType 操作类型
     * @param startDate 开始时间
     * @param endDate 结束时间
     * */
    List<SysOperLog> selectAll(@Param("start") int start,
                                   @Param("end") int end,
                                   @Param("loginName") String loginName,
                                   @Param("operType") String operType,
                                   @Param("startDate") Date startDate,
                                   @Param("endDate") Date endDate);

    /**
     * 获取所有日志数量
     * @param loginName 登录名
     * @param operType 操作类型
     * @param startDate 开始时间
     * @param endDate 结束时间
     * */
    int countSelectAll( @Param("loginName") String loginName,
                        @Param("operType") String operType,
                        @Param("startDate") Date startDate,
                        @Param("endDate") Date endDate);

    /**
     * 批量删除
     * @param loginName 登录名
     * @param operType 操作类型
     * @param startDate 开始时间
     * @param endDate 结束时间
     * */
    boolean deleteByQuery(@Param("loginName") String loginName,
                        @Param("operType") String operType,
                        @Param("startDate") Date startDate,
                        @Param("endDate") Date endDate);

    /**
     * 批量删除
     * @param loginName 登录名
     * @param operType 操作类型
     * @param startDate 开始时间
     * @param endDate 结束时间
     * @param notDelIds 非删除id列表
     * */
    boolean deleteByMap(@Param("loginName") String loginName,
                        @Param("operType") String operType,
                        @Param("startDate") Date startDate,
                        @Param("endDate") Date endDate,
                        @Param("notDelIds") List<String> notDelIds);

    /**
     * 根据列表删除
     * @param delIds 删除列表
     * */
    boolean deleteByList(@Param("delIds") List<String> delIds);
}